name: API CI/CD

on:
  push:
    branches: ["main"]
    tags: ["v*.*"]
  pull_request:
    branches: ["main"]


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Скачиваем код репозитория
        uses: actions/checkout@v6

      - name: Устанавливаем Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Устанавливаем зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Проверка кода линтером (Ruff)
        run: ruff check .

      - name: Запуск автотестов (Pytest)
        run: pytest -m "not docker"

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Скачиваем код
        uses: actions/checkout@v6

      - name: Устанавливаем Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Устанавливаем зависимости для тестов
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Извлечение метаданных образа Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ vars.DOCKER_USERNAME }}/predictor-api

      - name: Аутентификация в реестре
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Настройка Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Локальная сборка образа для теста
        uses: docker/build-push-action@v7
        with:
          push: false
          load: true
          tags: churn-api:test

      - name: Запуск контейнера
        run: docker run -d -p 8000:8000 --name churn-test churn-api:test

      - name: Ожидание готовности приложения
        run: sleep 5

      - name: Запуск тестов против контейнера
        run: pytest -m docker

      - name: Остановка контейнера
        if: always()
        run: docker stop churn-test

      - name: Сборка и отправка образа
        uses: docker/build-push-action@v7
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}